config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#play'

  post '/info', to: 'pages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :info, only: :play

  def play
  end

  def create
    color = params[:info][:color]
    name = params[:info][:name]
    session[:info] = { color: color, name: name }
    cookies[:color] = color
    cookies[:name] = name
    redirect_to action: :play
  end

  private

  def info
    return if session[:info].present?

    render 'info'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatchMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/info.html.erb
<% provide(:title, "Log in") %>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 style="text-align: center;">Info</h1>
    </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:info, url: info_path, method: :post) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :color %>
      <input class="form-control" type="text" name="info[color]" id="info_color">

      <%= f.submit "Play!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#info_color').colorpicker();
  });
</script>

app/views/pages/play.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.js"></script>
<style media="screen">
  html, body {
      overflow: hidden;
      margin: 0;
      padding: 0
  }
</style>
<script type="text/javascript">
  $(document).ready(function() {
    App.canvas = App.cable.subscriptions.create("CanvasChannel", {
      connected: function() {
        console.log('I connected');
        // Called when the subscription is ready for use on the server
      },

      disconnected: function() {
        console.log('I disconnected');
        // Called when the subscription has been terminated by the server
      },

      received: function(data) {
        // Called when there's incoming data on the websocket for this channel
        var user_info = data['user_info'];
        if (getCookie('name') == user_info['name'])
          return;
        initializeSubscriber(user_info);
        if (data['message'] == 'subscribed') {
          // do nothing
        }
        else if (data['message'] == 'unsubscribed') {
          removeDisconnectedSubscriber(user_info);
        }
        else if (data['message'] == 'move') {
          var coordinates = data['coordinates'];
          moveSubscriber(coordinates, user_info);
        }
      },

      move: function(coordinates) {
        return this.perform('move', { coordinates: coordinates });
      }
    });
    $(document).mousemove(function(event){
      App.canvas.move({ x: event.pageX, y: event.pageY });
    });
  });
</script>